name: Run Tests and Coverage

on: [push, pull_request]  # Se ejecuta al hacer push o crear un PR

jobs:
  test:
    runs-on: ubuntu-latest  # Usa un servidor Linux gratuito de GitHub

    steps:
      # 1. Descarga tu código
      - uses: actions/checkout@v4

      # 2. Configura Python (usa la versión de tu proyecto)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"  # Cambia según tu versión

      # 3. Instala dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Instala lo necesario para tests

      # 4. Ejecuta los tests con coverage
      - name: Run tests
        run: |
          pytest --cov=src src/tests/ --cov-report term-missing

      # 5. (Opcional) Sube el reporte a Codecov (solo si lo usas)
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3